### ISSUE TITLE
Ground truth timestamp

### ISSUE THREAD

**Issue by JzHuai0108** [visibilitydataset/visibilitydataset.github.io#8]
Dear authors,

From the ground truth gt csv files, I see the ground truth starts at time 0, and has a 200Hz rate.
The rosbag messages have unix time stamps which are very large values.
How do I associate the ground truth time t_1 and the ros message times t_2?

Also, for the handheld indoor sequences, I found the below calibration parameters,
```

dt_gt_ros:
  global_robust: 0.000
  global_unstable: -0.040
  global_aggressive: 0.115
  local_robust: 0.110
  local_unstable: 0.150
  local_aggressive: 0.225
  dark_robust: 0.25
  dark_unstable: 0.175
  dark_aggressive: 0.040
  varying_robust: 0.640
```
I am not sure the meaning of dt_gt_ros.
Does it mean 
a message's ros_time - the bag's start time + dt_gt_ros = the message's time according to the mocap system?
